CREATE TABLE [dbo].[Spells] (
    [Name]                  NVARCHAR (36)  NULL,
    [School]                NVARCHAR (13)  NULL,
    [Subschool]             NVARCHAR (23)  NULL,
    [Descriptor]            NVARCHAR (49)  NULL,
    [Spell_Level]           NVARCHAR (213) NULL,
    [Casting_Time]          NVARCHAR (47)  NULL,
    [Components]            NVARCHAR (191) NULL,
    [Costly_Components]     BIT            NULL,
    [Range]                 NVARCHAR (74)  NULL,
    [Area]                  NVARCHAR (94)  NULL,
    [Effect]                NVARCHAR (156) NULL,
    [Targets]               NVARCHAR (185) NULL,
    [Duration]              NVARCHAR (81)  NULL,
    [Dismissible]           BIT            NULL,
    [Shapeable]             BIT            NULL,
    [Saving_Throw]          NVARCHAR (73)  NULL,
    [Spell_Resistance]      NVARCHAR (40)  NULL,
    [Description]           NVARCHAR (MAX) NULL,
    [Description_Formatted] NVARCHAR (MAX) NULL,
    [Source]                NVARCHAR (44)  NULL,
    [Full_Text]             NVARCHAR (MAX) NULL,
    [Verbal]                NVARCHAR (226) NULL,
    [Somatic]               NVARCHAR (19)  NULL,
    [Material]              NVARCHAR (945) NULL,
    [Focus]                 BIT            NULL,
    [Divine_Focus]          BIT            NULL,
    [Sor]                   NVARCHAR (4)   NULL,
    [Wiz]                   NVARCHAR (4)   NULL,
    [Cleric]                NVARCHAR (4)   NULL,
    [Druid]                 NVARCHAR (4)   NULL,
    [Ranger]                NVARCHAR (4)   NULL,
    [Bard]                  NVARCHAR (4)   NULL,
    [Paladin]               NVARCHAR (4)   NULL,
    [Alchemist]             NVARCHAR (4)   NULL,
    [Summoner]              NVARCHAR (4)   NULL,
    [Witch]                 NVARCHAR (4)   NULL,
    [Inquisitor]            NVARCHAR (4)   NULL,
    [Oracle]                NVARCHAR (4)   NULL,
    [Antipaladin]           NVARCHAR (4)   NULL,
    [Magus]                 NVARCHAR (4)   NULL,
    [Adept]                 NVARCHAR (4)   NULL,
    [Deity]                 NVARCHAR (14)  NULL,
    [SLA_Level]             NVARCHAR (4)   NULL,
    [Domain]                NVARCHAR (83)  NULL,
    [Short_Description]     NVARCHAR (155) NULL,
    [Acid]                  BIT            NULL,
    [Air]                   BIT            NULL,
    [Chaotic]               BIT            NULL,
    [Cold]                  BIT            NULL,
    [Curse]                 BIT            NULL,
    [Darkness]              BIT            NULL,
    [Death]                 BIT            NULL,
    [Disease]               BIT            NULL,
    [Earth]                 BIT            NULL,
    [Electricity]           BIT            NULL,
    [Emotion]               BIT            NULL,
    [Evil]                  BIT            NULL,
    [Fear]                  BIT            NULL,
    [Fire]                  BIT            NULL,
    [Force]                 BIT            NULL,
    [Good]                  BIT            NULL,
    [Language_Dependent]    BIT            NULL,
    [Lawful]                BIT            NULL,
    [Light]                 BIT            NULL,
    [Mind_Affecting]        BIT            NULL,
    [Pain]                  BIT            NULL,
    [Poison]                BIT            NULL,
    [Shadow]                BIT            NULL,
    [Sonic]                 BIT            NULL,
    [Water]                 BIT            NULL,
    [Linktext]              NVARCHAR (32)  NULL,
    [Id]                    INT            NOT NULL,
    [Material_Costs]        NVARCHAR (5)   NULL,
    [Bloodline]             NVARCHAR (106) NULL,
    [Patron]                NVARCHAR (58)  NULL,
    [Mythic_Text]           NVARCHAR (896) NULL,
    [Augmented]             NVARCHAR (496) NULL,
    [Mythic]                BIT            NULL,
    [Bloodrager]            NVARCHAR (4)   NULL,
    [Shaman]                NVARCHAR (4)   NULL,
    [Psychic]               NVARCHAR (4)   NULL,
    [Medium]                NVARCHAR (4)   NULL,
    [Mesmerist]             NVARCHAR (4)   NULL,
    [Occultist]             NVARCHAR (4)   NULL,
    [Spiritualist]          NVARCHAR (4)   NULL,
    [Skald]                 NVARCHAR (4)   NULL,
    [Investigator]          NVARCHAR (4)   NULL,
    [Hunter]                NVARCHAR (4)   NULL,
    [Haunt_Statistics]      NVARCHAR (207) NULL,
    [Ruse]                  NVARCHAR (4)   NULL,
    [Draconic]              BIT            NULL,
    [Meditative]            BIT            NULL,
    [Summoner_Unchained]    NVARCHAR (6)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

